# Introducción keras en NLP

Ejemplo 1

In [5]:
import keras
import tensorflow as tf
frases= ['Hola mundo',
	'Hola a todos',
	'Hola a todo el mundo'
]

Tokenización con keras

Generar el diccionario de tokens

In [6]:
tokenizer = tf.keras.preprocessing.text.Tokenizer(num_words=10)
tokenizer.fit_on_texts(frases)
word_index = tokenizer.word_index
print(word_index)

{'hola': 1, 'mundo': 2, 'a': 3, 'todos': 4, 'todo': 5, 'el': 6}


Tokenizer para convertir las frases en secuencias de tokens.

In [9]:
secuencias=tokenizer.texts_to_sequences(frases)
print('secuencias = ',secuencias)

secuencias =  [[1, 2], [1, 3, 4], [1, 3, 5, 6, 2]]


Ejemplo de Tokenización con keras
método "pad_sequences" de la clase preprocessing.sequence para rellenar las secuencias de tokens a una longitud uniforme.

In [10]:
relleno = tf.keras.preprocessing.sequence.pad_sequences(secuencias)
print('relleno =\n ',relleno)



relleno =
  [[0 0 0 1 2]
 [0 0 1 3 4]
 [1 3 5 6 2]]


Ejemplo 2

In [12]:
import keras
import tensorflow as tf
frases= ['Hola mundo',
	'Hola a todos',
	'Hola a todo el mundo',
	'Feliz inicio de jornada'
]



tokenizer = tf.keras.preprocessing.text.Tokenizer(num_words=10)
tokenizer.fit_on_texts(frases)
word_index = tokenizer.word_index
print(word_index)


secuencias=tokenizer.texts_to_sequences(frases)
print('secuencias = ',secuencias)

relleno = tf.keras.preprocessing.sequence.pad_sequences(secuencias)
print('relleno =\n ',relleno)



{'hola': 1, 'mundo': 2, 'a': 3, 'todos': 4, 'todo': 5, 'el': 6, 'feliz': 7, 'inicio': 8, 'de': 9, 'jornada': 10}
secuencias =  [[1, 2], [1, 3, 4], [1, 3, 5, 6, 2], [7, 8, 9]]
relleno =
  [[0 0 0 1 2]
 [0 0 1 3 4]
 [1 3 5 6 2]
 [0 0 7 8 9]]


Ejemplo 3
El parámetro oov_token (out of vocabulary token)
En el Tokenizer de Keras se utiliza para especicar un token que se asignará a las palabras fuera del vocabulario durante el proceso de tokenización.

In [14]:
import keras
import tensorflow as tf
frases= ['Hola mundo',
	'Hola a todos',
	'Hola a todo el mundo'
	'Feliz inicio de jornada para todos'
]


tokenizer = tf.keras.preprocessing.text.Tokenizer(num_words=10,oov_token="<OOV>")
tokenizer.fit_on_texts(frases)
word_index = tokenizer.word_index
print(word_index)


secuencias=tokenizer.texts_to_sequences(frases)
print('secuencias = ',secuencias)

relleno = tf.keras.preprocessing.sequence.pad_sequences(secuencias)
print('relleno =\n ',relleno)


{'<OOV>': 1, 'hola': 2, 'a': 3, 'todos': 4, 'mundo': 5, 'todo': 6, 'el': 7, 'mundofeliz': 8, 'inicio': 9, 'de': 10, 'jornada': 11, 'para': 12}
secuencias =  [[2, 5], [2, 3, 4], [2, 3, 6, 7, 8, 9, 1, 1, 1, 4]]
relleno =
  [[0 0 0 0 0 0 0 0 2 5]
 [0 0 0 0 0 0 0 2 3 4]
 [2 3 6 7 8 9 1 1 1 4]]


Ejemplo 4


In [15]:
import keras
import tensorflow as tf
frases= ['Hola mundo',
	'Hola a todos',
	'Hola a todo el mundo'
	'Buen dia, Feliz inicio de jornada para todos'
]


tokenizer = tf.keras.preprocessing.text.Tokenizer(num_words=10,oov_token="<OOV>")
tokenizer.fit_on_texts(frases)
word_index = tokenizer.word_index
print(word_index)


secuencias=tokenizer.texts_to_sequences(frases)
print('secuencias = ',secuencias)


relleno = tf.keras.preprocessing.sequence.pad_sequences(secuencias,
                                                        padding='post',
                                                        truncating='post')

print('relleno =\n ',relleno)

{'<OOV>': 1, 'hola': 2, 'a': 3, 'todos': 4, 'mundo': 5, 'todo': 6, 'el': 7, 'mundobuen': 8, 'dia': 9, 'feliz': 10, 'inicio': 11, 'de': 12, 'jornada': 13, 'para': 14}
secuencias =  [[2, 5], [2, 3, 4], [2, 3, 6, 7, 8, 9, 1, 1, 1, 1, 1, 4]]
relleno =
  [[2 5 0 0 0 0 0 0 0 0 0 0]
 [2 3 4 0 0 0 0 0 0 0 0 0]
 [2 3 6 7 8 9 1 1 1 1 1 4]]
